# Generated by Django 5.0.6 on 2024-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, null=True, verbose_name="chegirmna"),
        ),
        migrations.AddField(
            model_name="product",
            name="true_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="oxirgi narx",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=0, null=True, verbose_name="Mahsul narxi"
            ),
        ),
    ]
