# Generated by Django 5.0.6 on 2024-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_discount_product_true_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(null=True, verbose_name="Maxulot miqdori"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=0, null=True, verbose_name="Maxulot narxi"
            ),
        ),
    ]
